name: CI CMake
on: [push, pull_request]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt-get install -y ninja-build llvm-11-tools

    - name: Compile LLVM C++ libraries with MSAN
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project --single-branch --branch llvmorg-11.0.0
        cd llvm-project
        mkdir build
        cd build
        cmake -GNinja ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DLLVM_USE_SANITIZER=MemoryWithOrigins -DLLVM_LIBC_ENABLE_LINTING=OFF -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON
        cmake --build . -- cxx cxxabi
        echo "LLVM_BUILD_DIR=`pwd`" >> $GITHUB_ENV
      env:
        CC: clang-11
        CXX: clang++-11

    - name: Generate project files
      run: |
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
      env:
        CC: clang-11
        CXX: clang++-11

    - name: Compile source code
      run: cmake --build . --config Release --verbose

    - name: Run test cases
      run: ctest --verbose -C Release --output-on-failure --max-width 120
      env:
        MSAN_OPTIONS: verbosity=0:abort_on_error=1
